CREATE TABLE IF NOT EXISTS "Objects" (
  "Id" INTEGER NOT NULL CONSTRAINT "PK_Objects" PRIMARY KEY AUTOINCREMENT,
  "Name" TEXT NOT NULL,
  "LastModified" TEXT NOT NULL DEFAULT '0001-01-01 00:00:00',
  "Progress" INTEGER NOT NULL DEFAULT 0

) 
